[package]
name = "message-db-interface"
version = "0.0.0"
edition = "2021"

[lib]
name = "msgdb"
crate-type = ["cdylib", "staticlib"]

[dependencies]
bitflags = "2.4.1"
cpp = "0.5.9"
microserde = "0.1.13"
rusqlite = "0.30.0"
ureq = "2.9.1"

[dev-dependencies]
rand = "0.8.5"
random = "0.14.0"
